##GLOBAL
TEST = False
PATH = "/home/aymeric/Desktop/Main/PROJECTS/tag/Reinforcment_Learning_Tag/tag"
NUM_CORES = 12

##SIMULATION
GAME_TIME = 150
NUM_SIMULATION = 100
AVG_SCORE = True


##ENVIRONMENT
WORLD_SIZE = 800
TARGET_REWARD = (WORLD_SIZE * GAME_TIME)//100
WALL_REWARD= -TARGET_REWARD 

##AGENT
IMAGE_SIZE = 10
INIT_X = WORLD_SIZE/2
INIT_Y = WORLD_SIZE/2
ACTION_DIC = {0:[0,-1],1:[0,1],2:[-1,0],3:[1,0],4:[0,0]}
FOV = 3

##GENETIC
MUTATION_FACTOR = 0.3
NUM_AGENT = 1000
BREED_FACTOR = 0.4


##BRAIN
INPUT_SIZE = 4
OUTPUT_SIZE = 4
BRAIN_SPEC = [INPUT_SIZE,3,OUTPUT_SIZE]


#VISUALS
IMAGE_SIZE = 10


#WORLD
N_AGENT = 100